### ISSUE TITLE
Failing to deploy to modulus with "modulus deploy"

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-meteor-react-router#64]
@exon I have a major issue with deploying to Modulus, this is the error I get:

```
Running command: npm start


> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main




/mnt/app/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/mnt/app/programs/server/boot.js:150:18)
    at webpack:///server.js:1:1
    at webpack:///server.js:4:1
    at /mnt/app/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/app/programs/server/node_modules/underscore/underscore.js:79:11)



npm
 ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR!
 node v0.10.40
npm ERR! 
npm  v3.8.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR!
 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!
     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle

npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log

Now using node v0.10.40

Found package.json: ./programs/server/package.json

Start script specified in package.json: node ../../main
```

Looks like npm in NOT installing what it should:

```
Compressing project...
29.2 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Node.js runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /programs/server/package.json
Installing node 0.10.40
Installing npm 3.8.0
Installing packages from /programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.5 install /mnt/input/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
meteor-dev-bundle@0.0.0 /mnt/input/programs/server
├── fibers@1.0.5
├─┬ meteor-promise@0.5.0
│ └─┬ promise@7.0.4
│   └── asap@2.0.3
├── semver@4.1.0
├─┬ source-map-support@0.3.2
│ └─┬ source-map@0.1.32
│   └── amdefine@1.0.0
└── underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
v0.10.40
deploy -> v0.10.40
Uploading completed build.
Provisioning and deploying bundle to servos...
```

Any idea here?
Please ...

[edit] looks like modulus deploy util is not installing dependencies :/

**Comment by eXon** [comment]
Is there any way to run npm install on your package.json file with modulus? Is your own package.json file is even on the server?

**Comment by eXon** [comment]
Just saw that the last version has the same problem with mupx. I'll try to find a fix ASAP.

**Comment by tomitrescak** [comment]
Thanks @eXon, I really appreciate that.

**Comment by tomitrescak** [comment]
Just so you know, the demetorised bundle does not contain package.json ;( The only package.json it has is the one from Meteor containing references to meteor packages.

<img width="278" alt="screen shot 2016-03-08 at 00 09 21" src="https://cloud.githubusercontent.com/assets/2682705/13570430/5036c958-e4c2-11e5-83ac-9f33faa91ff5.png">

**Comment by eXon** [comment]
Yea I know. I'll look for a way to bundle the dependencies in the private folder transparently.

**Comment by eXon** [comment]
If you update webpack:webpack this should be fixed. All your NPM dependencies (not devDependencies though) was deployed within your private folder in your server so Node.js can use it at runtime. I don't even understand how it was working before (maybe it was 1.3 I don't know).

This should fix your problem with modulus, it did with mupx.

**Comment by tomitrescak** [comment]
I'll test with modulus soon and report back

**Comment by tomitrescak** [comment]
Perfect. It works now!

**Comment by tomitrescak** [comment]
Great work. Thanks

**Comment by erperejildo** [comment]
How to update webpack:webpack?
I've got the same issue

**Comment by eXon** [comment]
@erperejildo Just like any Meteor package. Just type `meteor update`

**Comment by erperejildo** [comment]
Ah ok, it's another package. Anyway, I'm not using it and I've got the same problem
