### ISSUE TITLE
.babelrc support

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-meteor-react-router#65]
You are going to hate me ;) This is a non blocking issue, since it has an easy fix so very low priority ;) Issue is, when I use `.babelrc` I need to first build project without .babelrc and then I can add it. 

If I reset project and add `.babelrc` straight away following error appears:

```
=> Started proxy.
=> Started MongoDB.
webpack built 7cb59364ed069ff78e62 in 39380ms|
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):

   /Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13:
   The plugin "jsx-control-statements" didn't export a Plugin instance
   at PluginManager.validate
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
   at PluginManager.add
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
   at File.buildTransformers
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
   at new File
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
   at Pipeline.transform
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at
   /Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:58:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)


   While processing files with jsx (for target web.browser):

   /Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13:
   The plugin "jsx-control-statements" didn't export a Plugin instance
   at PluginManager.validate
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
   at PluginManager.add
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
   at File.buildTransformers
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
   at new File
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
   at Pipeline.transform
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at
   /Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:51:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)


   While processing files with ecmascript (for target os.osx.x86_64):

   /Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13:
   The plugin "jsx-control-statements" didn't export a Plugin instance
   at PluginManager.validate
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
   at PluginManager.add
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
   at File.buildTransformers
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
   at new File
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
   at Pipeline.transform
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at
   /Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/Users/tomi/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:58:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)


   While processing files with jsx (for target os.osx.x86_64):

   /Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13:
   The plugin "jsx-control-statements" didn't export a Plugin instance
   at PluginManager.validate
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
   at PluginManager.add
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
   at File.buildTransformers
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
   at new File
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
   at Pipeline.transform
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at
   /Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/Users/tomi/.meteor/packages/jsx/.0.2.3.12mxewd++os+web.browser+web.cordova/plugin.compile-jsx.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:51:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)


=> Your application has errors. Waiting for file change.
```

**Comment by eXon** [comment]
The `ecmascript` and `jsx` package shuldn't be in your project. I'm not sure what's going on. I'll try to replicate when I have some time.

**Comment by tomitrescak** [comment]
That's why I was in shock as well ... they are definitely not the part of the packages I have in the project.

**Comment by ejfrancis** [comment]
yup I see this same error when using `webpack:webpack` and `webpack:vue`, if I add the `babel-plugin-transform-object-rest-spread` to .babelrc file I get the error

```
 /Users/efrancis/.meteor/packages/ecmascript/.0.1.6.1u7vk5v++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13:
   The plugin "transform-object-rest-spread" didn't export a Plugin instance
```

If I remove the .babelrc file, build the project without it, then add it back it works fine

**Comment by eXon** [comment]
Shouldn't be a problem now.
